server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: video-api-service
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/videodb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: ${JPA_SHOW_SQL:false}

app:
  storage:
    upload-dir: ${VIDEO_UPLOAD_DIR:/tmp/fiap-x/uploads}
  sqs:
    queues:
      video-uploaded: ${AWS_SQS_VIDEO_UPLOADED_QUEUE:video-uploaded-queue}
